"""Admin helpers for setting up campaigns and running lotteries against the live backend."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional

import httpx

from simulator.config import settings

logger = logging.getLogger(__name__)


async def get_admin_token(client: Optional[httpx.AsyncClient] = None) -> str:
    """Authenticate with Supabase as admin and return JWT access token."""
    url = f"{settings.supabase_url.rstrip('/')}/auth/v1/token?grant_type=password"
    headers = {
        "apikey": settings.supabase_anon_key,
        "Content-Type": "application/json",
    }
    payload = {
        "email": settings.admin_email,
        "password": settings.admin_password,
    }

    close_client = False
    if client is None:
        client = httpx.AsyncClient(timeout=30.0)
        close_client = True

    try:
        resp = await client.post(url, headers=headers, json=payload)
        resp.raise_for_status()
        data = resp.json()
        token = data.get("access_token")
        if not token:
            raise ValueError(f"No access_token returned by Supabase auth: {data}")
        return token
    finally:
        if close_client:
            await client.aclose()


async def create_test_campaign(
    admin_token: str,
    capacity: int = 50,
    title: str = "Simulated Live Campaign",
    duration_minutes: int = 60,
    client: Optional[httpx.AsyncClient] = None,
) -> Dict[str, Any]:
    """Create a campaign and publish it via Dhruv's FastAPI admin endpoints."""
    close_client = False
    if client is None:
        client = httpx.AsyncClient(base_url=settings.backend_url, timeout=30.0)
        close_client = True

    headers = {
        "Authorization": f"Bearer {admin_token}",
        "Content-Type": "application/json",
    }

    now = datetime.now(timezone.utc)
    reg_start = now.isoformat()
    reg_end = (now + timedelta(minutes=duration_minutes)).isoformat()

    campaign_payload = {
        "title": title,
        "description": "Adversarial test campaign generated by Fair Drop live simulator",
        "total_capacity": capacity,
        "registration_start": reg_start,
        "registration_end": reg_end,
    }

    try:
        # Create campaign
        create_resp = await client.post(
            "/api/v1/admin/campaigns",
            headers=headers,
            json=campaign_payload,
        )
        create_resp.raise_for_status()
        campaign = create_resp.json()
        campaign_id = campaign.get("id") or campaign.get("campaign_id")

        if not campaign_id:
            raise ValueError(f"Failed to obtain campaign_id from response: {campaign}")

        # Transition campaign lifecycle: prepare -> publish if endpoints exist
        # Best effort lifecycle transitions per architecture spec
        for action in ["prepare", "publish"]:
            try:
                act_resp = await client.post(
                    f"/api/v1/admin/campaigns/{campaign_id}/{action}",
                    headers=headers,
                )
                if act_resp.status_code < 400:
                    logger.info(f"Campaign {campaign_id} {action} succeeded")
            except Exception as e:
                logger.warning(f"Optional campaign lifecycle action {action} warning: {e}")

        return campaign
    finally:
        if close_client:
            await client.aclose()


async def run_lottery(
    admin_token: str,
    campaign_id: str,
    client: Optional[httpx.AsyncClient] = None,
) -> Dict[str, Any]:
    """Close registration, freeze, and draw winners for a campaign."""
    close_client = False
    if client is None:
        client = httpx.AsyncClient(base_url=settings.backend_url, timeout=60.0)
        close_client = True

    headers = {
        "Authorization": f"Bearer {admin_token}",
        "Content-Type": "application/json",
    }

    try:
        # Close registration
        try:
            await client.post(f"/api/v1/admin/campaigns/{campaign_id}/close", headers=headers)
        except Exception as e:
            logger.warning(f"Campaign close step: {e}")

        # Freeze pool
        try:
            await client.post(f"/api/v1/admin/campaigns/{campaign_id}/freeze", headers=headers)
        except Exception as e:
            logger.warning(f"Campaign freeze step: {e}")

        # Draw lottery
        draw_resp = await client.post(
            f"/api/v1/admin/campaigns/{campaign_id}/draw",
            headers=headers,
        )
        draw_resp.raise_for_status()
        return draw_resp.json()
    finally:
        if close_client:
            await client.aclose()
