"""Reporter module for generating JSON, CSV, and Markdown judge reports."""

from __future__ import annotations

import csv
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from simulator.metrics.collector import RequestOutcome

logger = logging.getLogger(__name__)

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


def write_reports(
    analysis: Dict[str, Any],
    raw_outcomes: List[RequestOutcome],
) -> Dict[str, Path]:
    """Write scenario execution reports in JSON, CSV, and Markdown format."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    scenario = analysis.get("scenario", "scenario")
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    json_path = REPORTS_DIR / f"{scenario}_{timestamp}.json"
    latest_json_path = REPORTS_DIR / "latest.json"
    csv_path = REPORTS_DIR / f"{scenario}_{timestamp}.csv"
    md_path = REPORTS_DIR / f"{scenario}_{timestamp}.md"

    # 1. JSON Report
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2)

    with open(latest_json_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2)

    # 2. CSV Report (Raw Request Logs)
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp", "client_class", "user_id", "endpoint",
            "method", "status_code", "latency_ms", "idempotency_key",
            "request_id", "is_retry"
        ])
        for o in raw_outcomes:
            writer.writerow([
                o.timestamp, o.client_class, o.user_id, o.endpoint,
                o.method, o.status_code, o.latency_ms, o.idempotency_key or "",
                o.request_id or "", o.is_retry
            ])

    # 3. Markdown Judge Report
    md_content = _build_markdown_report(analysis)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    logger.info(f"Reports successfully written to {REPORTS_DIR}")
    return {
        "json": json_path,
        "latest": latest_json_path,
        "csv": csv_path,
        "markdown": md_path,
    }


def _build_markdown_report(analysis: Dict[str, Any]) -> str:
    """Build a judge-ready markdown presentation report."""
    scenario = analysis.get("scenario", "Scenario")
    total_reqs = analysis.get("total_requests", 0)
    lat = analysis.get("overall_latency", {})
    ratio = analysis.get("bot_advantage_ratio", 1.0)
    h_win = analysis.get("human_win_rate", 0.0)
    b_win = analysis.get("bot_win_rate", 0.0)
    assertions = analysis.get("integrity_assertions", {})
    classes = analysis.get("per_class_stats", {})

    lines = [
        f"# Fair Drop Live Adversarial Report — {scenario.upper()}",
        "",
        "## Executive Summary",
        f"- **Bot Advantage Ratio**: `{ratio}x` (Target: ~1.00x, Zero Bot Advantage)",
        f"- **Human Win Rate**: `{h_win * 100:.1f}%`",
        f"- **Bot Win Rate**: `{b_win * 100:.1f}%`",
        f"- **Total HTTP Requests**: `{total_reqs}`",
        f"- **P95 Latency**: `{lat.get('p95', 0):.2f} ms` | **P99 Latency**: `{lat.get('p99', 0):.2f} ms`",
        "",
        "## System Integrity & Safety Assertions",
        "| Assertion | Status | Detail |",
        "|---|---|---|",
        f"| Double Registration Blocked | {'✅ PASS' if assertions.get('idempotency_preserved') else '❌ FAIL'} | Double registrations: {assertions.get('double_registration_count', 0)} |",
        f"| Direct API Bypass Blocked | {'✅ PASS' if assertions.get('zero_unauthorized_direct_access') else '❌ FAIL'} | 403 Forbidden enforced on unpermitted registers |",
        f"| Bot Neutralization | {'✅ PASS' if assertions.get('bot_advantage_neutralized') else '❌ FAIL'} | Ratio: {ratio}x (Acceptable: <= 1.25x) |",
        "",
        "## Profile Breakdown",
        "| Profile Class | Users | Requests | Succeeded | Blocked | Win Rate | P50 (ms) | P95 (ms) |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for cls_name, stat in classes.items():
        c_lat = stat.get("latency", {})
        lines.append(
            f"| `{cls_name}` | {stat.get('user_count', 0)} | {stat.get('total_requests', 0)} | "
            f"{stat.get('successful_requests', 0)} | {stat.get('blocked_requests', 0)} | "
            f"{stat.get('win_rate', 0.0) * 100:.1f}% | {c_lat.get('p50', 0):.1f} | {c_lat.get('p95', 0):.1f} |"
        )

    lines.extend([
        "",
        "---",
        "*Generated by Fair Drop Live Adversarial Simulator via Antigravity*",
    ])

    return "\n".join(lines)
